when@dev:
    web_profiler:
        toolbar: true

    framework:
        trusted_proxies: '127.0.0.1,REMOTE_ADDR'
        trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-port', 'x-forwarded-proto', 'x-forwarded-prefix']
        profiler:
            collect_serializer_data: true

when@test:
    framework:
        profiler:
            collect: false
            collect_serializer_data: true
